import { NextApiRequest, NextApiResponse } from "next";

const cityNames = [
    "Agartala",
    "Agra",
    "Ahmedabad",
    "Ahmednagar",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Allahabad",
    "Alwar",
    "Amaravati",
    "Ambala",
    "Amravati",
    "Amritsar",
    "Anand",
    "Anantapur",
    "Asansol",
    "Aurangabad",
    "Bareilly",
    "Bathinda",
    "Belagavi",
    "Bengaluru",
    "Berhampur",
    "Bhagalpur",
    "Bharatpur",
    "Bharuch",
    "Bhavnagar",
    "Bhilai",
    "Bhilwara",
    "Bhiwandi",
    "Bhopal",
    "Bhubaneswar",
    "Bidar",
    "Bikaner",
    "Bilaspur",
    "Bokaro Steel City",
    "Burdwan",
    "Chandigarh",
    "Chandrapur",
    "Chennai",
    "Chittoor",
    "Coimbatore",
    "Cuttack",
    "Darbhanga",
    "Davangere",
    "Dehradun",
    "Delhi",
    "Dhanbad",
    "Dharamshala",
    "Dibrugarh",
    "Dindigul",
    "Durgapur",
    "Erode",
    "Faridabad",
    "Firozabad",
    "Gandhinagar",
    "Gangtok",
    "Gaya",
    "Ghaziabad",
    "Gorakhpur",
    "Gulbarga",
    "Guntur",
    "Gurugram",
    "Guwahati",
    "Gwalior",
    "Haldwani",
    "Haridwar",
    "Hisar",
    "Hubballi",
    "Hyderabad",
    "Imphal",
    "Indore",
    "Itanagar",
    "Jabalpur",
    "Jaipur",
    "Jalandhar",
    "Jalgaon",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jhansi",
    "Jodhpur",
    "Jorhat",
    "Kakinada",
    "Kannur",
    "Kanpur",
    "Karimnagar",
    "Karnal",
    "Kochi",
    "Kohima",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Kota",
    "Kozhikode",
    "Kurnool",
    "Lucknow",
    "Ludhiana",
    "Madurai",
    "Malappuram",
    "Mangaluru",
    "Mathura",
    "Meerut",
    "Moradabad",
    "Mumbai",
    "Muzaffarpur",
    "Mysuru",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Navi Mumbai",
    "Nellore",
    "Noida",
    "Panaji",
    "Panipat",
    "Patiala",
    "Patna",
    "Pondicherry",
    "Prayagraj",
    "Pune",
    "Raipur",
    "Rajahmundry",
    "Rajkot",
    "Ranchi",
    "Ratlam",
    "Rewa",
    "Rohtak",
    "Rourkela",
    "Sagar",
    "Salem",
    "Sambalpur",
    "Satna",
    "Shillong",
    "Shimla",
    "Silchar",
    "Siliguri",
    "Solapur",
    "Sonipat",
    "Srinagar",
    "Surat",
    "Thane",
    "Thanjavur",
    "Thiruvananthapuram",
    "Thoothukudi",
    "Thrissur",
    "Tiruchirappalli",
    "Tirupati",
    "Tiruppur",
    "Tumakuru",
    "Udaipur",
    "Ujjain",
    "Vadodara",
    "Varanasi",
    "Vasai-Virar",
    "Vellore",
    "Vijayawada",
    "Visakhapatnam",
    "Warangal"
];

const cities = cityNames.map((city) => ({
    label: city,
    value: city.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "")
}));

function getCities(req: NextApiRequest, res: NextApiResponse) {
    const filter = typeof req.query.filter === "string" ? req.query.filter.trim().toLowerCase() : "";

    if (filter) {
        return res.json({
            data: cities.filter((city) => city.label.toLowerCase().includes(filter))
        });
    }

    return res.json({ data: cities });
}

export default getCities;
